name: Build 
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.10
          
      - name: Build Beacon Mock
        run: cd ${GITHUB_WORKSPACE}/beacon && go build .
